---
name: Bug Report
description: Report errors or unexpected behavior in the Critter System.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue with the Critter System. Your feedback helps us improve the platform.

        Please provide detailed information below to help us diagnose and fix the problem.    
  - type: dropdown
    attributes:
      label: User Role
      description: Select your role when you encountered the issue.
      options:
        - Critter System Staff
        - Eurofurence Director
        - Eurofurence Staff
        - Attendee (Critter)
  - type: textarea
    attributes:
      label: Describe the solution you'd like to see implemented
      placeholder: Detail the solution or feature you would like to see added to the Critter System.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How would this feature improve the Critter System for Eurofurence volunteers or attendees?
      placeholder: Explain how this feature would enhance the experience or efficiency for those using the system during Eurofurence.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe any alternatives you've considered or tried
      placeholder: Mention any alternative solutions or workarounds you have considered or used, and why they might not be sufficient.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context or screenshots
      placeholder: Provide any other relevant details, screenshots, or context that would help us understand your feature request better.
    validations:
      required: false
