---
name: Bug Report
description: Report errors or unexpected behavior you encountered with Eurofurence Critter System.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue with the Critter System. Your feedback helps us improve the platform.

        Please provide detailed information below to help us diagnose and fix the problem.    
 - type: dropdown
    attributes:
      label: Installation source
      multiple: false
      options:
        - Static binary from official website
        - Microsoft Store
        - Mac App Store
        - Flatpak
        - Snap
        - Other (unofficial) source
    validations:
      required: true
