blank_issues_enabled: false
contact_links:
  - name: General Questions or Issues
    url: https://help.eurofurence.org/contact/it
    about: For any other questions or problems, please contact the Eurofurence IT Department.
